# Generated by Django 3.0.8 on 2020-07-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeaStall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, verbose_name='Username')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('payments', models.CharField(max_length=120, verbose_name='Payments')),
                ('address', models.TextField(verbose_name='Address')),
            ],
        ),
    ]
